{{ if .Values.certmanager.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "gatekeeper.fullname" . }}.{{ .Release.Namespace }}.svc
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ template "gatekeeper.fullname" . }}.{{ .Release.Namespace }}.svc-tls
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The {{ .Release.Namespace }} value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
  commonName: "{{ template "gatekeeper.fullname" . }} server"
  organization:
  - One Concern CA
  dnsNames:
  - {{ template "gatekeeper.fullname" . }}
  - "127.0.0.1"
  - "::1"
  - localhost
  - {{ template "gatekeeper.fullname" . }}.{{ .Release.Namespace }}
  - {{ template "gatekeeper.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ template "gatekeeper.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
{{ end }}
