apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gatekeeper.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gatekeeper.name" . }}
    helm.sh/chart: {{ include "gatekeeper.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: |
{{ toYaml .Values.config.keys | indent 4 }}

