apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatekeeper.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gatekeeper.name" . }}
    helm.sh/chart: {{ include "gatekeeper.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  clientSecret: {{ .Values.clientSecret | b64enc | quote }}
  encryptionKey: {{ .Values.encryptionKey | b64enc | quote }}
