clientSecret: ENC[AES256_GCM,data:Pl1Fak4zlIV4w8lBZFdpQdWU2j7OVx6JL2d2DnONm7utaIeC,iv:kmZ5vNVd50U7UF51279o4i6tEhWNfr/N5oxRCCnR0BU=,tag:VOqh7Z/pKU4iLEA7LQ+ZFg==,type:str]
encryptionKey: ENC[AES256_GCM,data:WIi/ZBHn0XChhf6/LvfkJ+8nfl5GWHJk766Mqoq4RBs=,iv:87lgCZpOS2PSZhaDIL9kEB3irkPUQlfHBR3RqGFRCxM=,tag:z5sw0sjaw5hoXJURs/5ztg==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/onec-co/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2019-02-24T22:20:24Z'
        enc: CiQANPTHQA5PBULZs6riyGjetX7FSGnfZ+scHZz8JBMJSD0F6vMSSQDDBPFaIowzey0OgY/U3ybesnOb2TsVyKQMDsz+cPhZW7Bk38scfvL0P2fcufLtDpLo5BvdbX3s13mf8SLsBFUY/bsua/xszOQ=
    azure_kv: []
    lastmodified: '2019-02-24T22:20:25Z'
    mac: ENC[AES256_GCM,data:iTaNE7TzbG8u8ZbYoBe9GQcI773sjinoOXyjWockGezoFfK2zDwIVUuLBjAaC2JWK26i477CMvUbH8iy1M/CF6CMUzOeTnEFOPwywPD8AmZC2Afp49FQ7lyeTZQ37p7Q352RDF8n7fbKOyraNN5rvWyIod8FK2HRtXLy/jkAldo=,iv:lB4dkHQk16Eev9qa40Bg7lMBM48sd3bUchmedqpX4t8=,tag:RRCCQoLEfiIalSRMhbqsVg==,type:str]
    pgp: []
    unencrypted_suffix: .dec
    version: 3.2.0
